### PR TITLE
fix: improve PKCE validation and random generator

### LINKED ISSUE #8: don't use '=' padding in base64 URL encoding of S256 code challenge method, be strict about any additional characters
(Hello! It's really cool to find a Go implementation for the IndieAuth spec! I've also implemented one; see https://github.com/shurcooL/home/issues/34 and https://github.com/shurcooL/home/issues/43. When trying to sign in to your site which I understand uses this package, I found a problem and wanted to report it.)

I believe there's a small bug in the PKCE verification as currently implemented in the latest version of this package, to do with padding used in base64 encoding.

The IndieAuth spec defers to RFC 7636 for PKCE details:

> All IndieAuth clients MUST use PKCE ([[RFC7636](https://indieauth.spec.indieweb.org/#bib-rfc7636)]) to protect against authorization code injection and CSRF attacks. A non-canonical description of the PKCE mechanism is described below, but implementers should refer to [[RFC7636](https://indieauth.spec.indieweb.org/#bib-rfc7636)] for details.

_(Source: https://indieauth.spec.indieweb.org/#authorization-request.)_

RFC 7636 section 4.6 (https://datatracker.ietf.org/doc/html/rfc7636#section-4.6) details how the code challenge method verification is done:

> If the "code_challenge_method" from [Section 4.3](https://datatracker.ietf.org/doc/html/rfc7636#section-4.3) was "S256", the received "code_verifier" is hashed by SHA-256, base64url-encoded, and then compared to the "code_challenge", i.e.:
>
> `BASE64URL-ENCODE(SHA256(ASCII(code_verifier))) == code_challenge`
>
> [...] If the values are not equal, an error response indicating "invalid_grant" as described in [Section 5.2 of [RFC6749]](https://datatracker.ietf.org/doc/html/rfc6749#section-5.2) MUST be returned.

In https://datatracker.ietf.org/doc/html/rfc7636#section-3 it is defined that "Base64url Encoding" refers to URL encoding without padding:

> Base64 encoding using the URL- and filename-safe character set defined in [Section 5 of [RFC4648]](https://datatracker.ietf.org/doc/html/rfc4648#section-5), **with all trailing '=' characters omitted** ([...]) and **without** the inclusion of any line breaks, whitespace, **or other additional characters**.  (See [Appendix A](https://datatracker.ietf.org/doc/html/rfc7636#appendix-A) for notes on implementing base64url encoding without padding.)

(Emphasis mine.)

Go's [base64.RawURLEncoding](https://pkg.go.dev/encoding/base64#RawURLEncoding) implements URL base64 encoding without padding, and can be used instead of `base64.URLEncoding`.

I'll send a PR that fixes this issue in case you find it helpful.

### LINKED ISSUE #9: use crypto/rand for generating high-entropy cryptographic random values
https://datatracker.ietf.org/doc/html/rfc7636#section-4.1 defines `code_verifier` to be a "high-entropy cryptographic random STRING", and notes:

> NOTE: The code verifier SHOULD have enough entropy to make it
> impractical to guess the value.  It is RECOMMENDED that the output of
> a **suitable random number generator** be used to create a 32-octet
> sequence.  The octet sequence is then base64url-encoded to produce a
> 43-octet URL safe string to use as the code verifier.

(Emphasis mine.)

The `math/rand` Go package isn't suitable for that purpose; the `crypto/rand` package can be used in its place.

I'll send a PR that fixes this issue in case you find it helpful.

### PR DESCRIPTION
**Pull request by dmitshur**
Use base64.RawURLEncoding, not base64.URLEncoding, for the S256 code
challenge method.

Use crypto/rand, not math/rand, for high-entropy cryptographic random
values.

Fixes #8.
Fixes #9.

### CODE REVIEW

File: client.go [hunk 1]
```diff
@@ -159,6 +161,18 @@ func (c *Client) Authenticate(profile, scope string) (*AuthInfo, string, error)
...
 }
 
+// newState generates a new state value.
+func newState() string {
+	// OAuth 2.0 requires state to be printable ASCII, so base64 fits.
+	// See https://datatracker.ietf.org/doc/html/rfc6749#appendix-A.5.
+	b := make([]byte, 64)
+	_, err := cryptorand.Read(b)
+	if err != nil {
+		panic(err)
```
Comment (hacdias) [inline client.go]: I don't feel particularly safe panicking here. I understand that this should never happen, but why panic and not return an error?

Comment (dmitshur) [reply client.go]: Hmm, my rationale to handle the error this way has been that I couldn't think of a scenario where the source of entropy on the system would be exhausted to a point of getting an error from `crypto/rand.Read`, and there being anything useful to do other than abruptly stopping execution due to an internal error. (I've not observed any occurrences so far, and so never had the need to revisit this simple error handling strategy.)

Returning an error to the user is another viable strategy, though it incurs the cost onto the user of needing to think about it. Since this is a library, not a command, and it's possible some users might want to have finer control over how this error is handled, so that might be a good path to take.

Changed it to return the error to the caller, PTAL.

**Comment by hacdias** [comment]
@dmitshur thanks a lot for this. I'm going to merge it in a different branch so i can make a few modifications before merging on main. See #11.

**Comment by dmitshur** [comment]
Sounds good, thank you for reviewing and merging!

(Next time I'll check the "Allow edits by maintainers" bit so you can reuse this PR.)
